### ISSUE TITLE
Frame of report

### ISSUE THREAD

**Issue by DUQ-01** [BoXun97/DS4D_GroupProject#3]
Can I state our design goal in INTRODUCTION part?
But we decide what our design goal is was after analysis of data, is the sequence no problem?

**Comment by tongtong-design** [comment]
I think it is ok to mention the goal introduction part, which can play the role of the general starting point question. After data analysis, the process of determining the goal can be written in detail about how to determine the goal, and then the purpose of the goal and the starting point question can be reaffirmed, which will be a little more logical.Does it help?
