### ISSUE TITLE
Number of LDA Topics

### ISSUE THREAD

**Issue by Xhuiii** [BoXun97/DS4D_GroupProject#4]
There are different types of LDA models. I am not sure which LDA model we should use? 3-topics one? 5-topics one? Or 10-topics one?

**Comment by DUQ-01** [comment]
There are generally two criteria for judging whether an LDA model is reasonable, one is coherence score and the other is perplexity score. That is, the greater the number of topics, the lower the perplexity score of the model, but note that when there are a large number of topics, the generated model tends to overfit, so you cannot rely solely on the perplexity score to judge the quality of a model. When we understand the approximate range of the number of topics from the perplexity, we can use coherence score to select more suitable topics from this range.

**Comment by Xhuiii** [comment]
Great!

**Comment by DUQ-01** [comment]
You are welcome
